"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var points_1 = require("./points");
var p = new points_1.Point(0, 0);
var p2 = new points_1.Point(Math.floor(Math.random() * 10), Math.floor(Math.random() * 10));
var p3 = new points_1.Point(Math.floor(Math.random() * 10), Math.floor(Math.random() * 10));
var p4 = new points_1.Point(Math.floor(Math.random() * 10), Math.floor(Math.random() * 10));
var p5 = new points_1.Point(Math.floor(Math.random() * 10), Math.floor(Math.random() * 10));
var arrP = [p2, p3, p4, p5];
p.setX(30);
p.setY(4);
console.log("Valor eje x: " + p.getX());
console.log("Valor eje y: " + p.getY());
console.log(p.toString());
console.log("La distancia es : " + p.distanceTolOrigin());
console.log("La distancia entre (" + p.getX() + "," + p.getY() + ") y (" + p2.getX() + "," + p2.getY() + ") es: " + p.calculateDistance(p2));
console.log(p.calcularQuadrant());
console.log("--------------------------------------------------------------------");
console.log(arrP);
console.log(p.calculateNearest(arrP));
