"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var buclesFor_1 = require("./buclesFor");
var condicionales_1 = require("./condicionales");
var arr1 = ["Casa", "Coche", "Ciudad", "Cesta"];
var arr2 = ["Barco", "Baca", "Bicicleta", "Balon", "Bisiesto", "Brasil"];
var arr3 = ["Venezuela", "Veneno", "Voltaje"];
(0, condicionales_1.esParImpar)((0, buclesFor_1.sumaCaracteres)(arr1));
(0, condicionales_1.esParImpar)((0, buclesFor_1.sumaCaracteres)(arr2));
(0, condicionales_1.esParImpar)((0, buclesFor_1.sumaCaracteres)(arr3));
